SCR_FactionCallsignInfo {
 m_bIsAssignedRandomly 0
 m_aCompanyNames {
  SCR_CallsignInfo "{69388CF4782B8C77}" {
   m_sCallsign "Hitman"
  }
 }
 m_iCompanyOverflowIndex 1
 m_aPlatoonNames {
  SCR_CallsignInfo "{69388CF4782B8C9C}" {
   m_sCallsign "Hitman"
  }
  SCR_CallsignInfo "{69388CF4782B8C9D}" {
   m_sCallsign "Ares"
  }
  SCR_CallsignInfo "{69388CF4782B8C9A}" {
   m_sCallsign "Fenrir"
  }
  SCR_CallsignInfo "{69388CF4782B8C9B}" {
   m_sCallsign "Sabre"
  }
  SCR_CallsignInfo "{69388CF463A301B6}" {
   m_sCallsign "Misfit"
  }
 }
 m_aSquadNames {
  SCR_CallsignInfo "{69388CF4782B8C99}" {
   m_sCallsign "Blue"
  }
  SCR_CallsignInfo "{69388CF4782B8C83}" {
   m_sCallsign "Red"
  }
  SCR_CallsignInfo "{69388CF4782B8C80}" {
   m_sCallsign "Playtime"
  }
 }
 m_sCallsignGroupFormat "%2 %3"
 m_sCallsignCharacterFormat "%2 %3: %4"
 m_sCallsignCharacterWithRoleFormat "%2 %3: %4"
 m_aCharacterRoleCallsigns {
  SCR_LeaderRoleCallsign "{69388CF4782B8CBF}" {
   m_sRoleName "#AR-Callsign_US_SquadLeader"
  }
  SCR_RadioOperatorRoleCallsign "{69388CF4782B8CBD}" {
   m_sRoleName "#AR-Callsign_US_RadioOperator"
  }
  SCR_PlayerLeaderRoleCallsign "{69388CF4782B8CBA}" {
   m_sRoleName "#AR-Callsign_US_SquadLeader"
   m_eRoleAvailableForCharacterType PLAYER_ONLY
  }
 }
}