SCR_EntityCatalogMultiList {
 m_eEntityCatalogType CHARACTER
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{6938D5A667803CCC}" {
   m_sIdentifier "Players"
   m_aEntities {
    SCR_EntityCatalogEntry "{6938D5A6501FDF98}" {
     m_sEntityPrefab "{00E48D2F9476A299}Prefabs/Characters/Character_RTG_AntiTank.et"
     m_aEntityDataList {
      SCR_EntityCatalogSpawnerData "{5DF6957609E74636}" {
       m_eSlotTypes GROUP_SMALL
      }
      SCR_EntityCatalogLoadoutData "{608AAACB83789355}" {
       m_fSpawnSupplyCost 48
      }
     }
    }
    SCR_EntityCatalogEntry "{6938D5A648F6E61D}" {
     m_sEntityPrefab "{78F1EDA47B24F348}Prefabs/Characters/Character_RTG_Autorifleman.et"
     m_aEntityDataList {
      SCR_EntityCatalogSpawnerData "{6938D5A648F6E661}" {
       m_eSlotTypes GROUP_SMALL
      }
      SCR_EntityCatalogLoadoutData "{6938D5A648F6E69C}" {
       m_fSpawnSupplyCost 48
      }
     }
    }
    SCR_EntityCatalogEntry "{6938D5A6461D9C52}" {
     m_sEntityPrefab "{2282FDD9DDACD45E}Prefabs/Characters/Character_RTG_TeamLeader.et"
     m_aEntityDataList {
      SCR_EntityCatalogSpawnerData "{6938D5A6461D9CBF}" {
       m_eSlotTypes GROUP_SMALL
      }
      SCR_EntityCatalogLoadoutData "{6938D5A6461D9CBA}" {
       m_fSpawnSupplyCost 48
      }
     }
    }
    SCR_EntityCatalogEntry "{6938D5A646B9530D}" {
     m_sEntityPrefab "{9BF0C6E6FCCACDDA}Prefabs/Characters/Character_RTG_Medic.et"
     m_aEntityDataList {
      SCR_EntityCatalogSpawnerData "{6938D5A646B9536B}" {
       m_eSlotTypes GROUP_SMALL
      }
      SCR_EntityCatalogLoadoutData "{6938D5A646B95366}" {
       m_fSpawnSupplyCost 48
      }
     }
    }
    SCR_EntityCatalogEntry "{6938D5A6474C38A5}" {
     m_sEntityPrefab "{F7651E7733323D4C}Prefabs/Characters/Character_RTG_AmmoBearer.et"
     m_aEntityDataList {
      SCR_EntityCatalogSpawnerData "{6938D5A6474C3B12}" {
       m_eSlotTypes GROUP_SMALL
      }
      SCR_EntityCatalogLoadoutData "{6938D5A6474C3B10}" {
       m_fSpawnSupplyCost 48
      }
     }
    }
   }
  }
 }
}