SCR_EntityCatalogMultiList {
 m_eEntityCatalogType CHARACTER
 m_aEntityEntryList {
  SCR_EntityCatalogEntry "{693A9951F36898FD}" {
   m_sEntityPrefab "{00E48D2F9476A299}Prefabs/Characters/Role Loadouts/Character_RTG_AntiTank.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{6052CE8EFD185AFB}" {
     m_eValidEditorModes 33
    }
    SCR_EntityCatalogSpawnerData "{5C727350682F8293}" {
     m_eSlotTypes GROUP_SMALL
    }
   }
  }
  SCR_EntityCatalogEntry "{693A9951ED9253A8}" {
   m_sEntityPrefab "{78F1EDA47B24F348}Prefabs/Characters/Role Loadouts/Character_RTG_Autorifleman.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{6052CE8EFD185AFB}" {
     m_eValidEditorModes 33
    }
    SCR_EntityCatalogSpawnerData "{5C727350682F8293}" {
     m_eSlotTypes GROUP_SMALL
    }
   }
  }
  SCR_EntityCatalogEntry "{693A9951ECD33B00}" {
   m_sEntityPrefab "{F7651E7733323D4C}Prefabs/Characters/Role Loadouts/Character_RTG_AmmoBearer.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{6052CE8EFD185AFB}" {
     m_eValidEditorModes 33
    }
    SCR_EntityCatalogSpawnerData "{5C727350682F8293}" {
     m_eSlotTypes GROUP_SMALL
    }
   }
  }
  SCR_EntityCatalogEntry "{693A9951EC22E163}" {
   m_sEntityPrefab "{9BF0C6E6FCCACDDA}Prefabs/Characters/Role Loadouts/Character_RTG_Medic.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{6052CE8EFD185AFB}" {
     m_eValidEditorModes 33
    }
    SCR_EntityCatalogSpawnerData "{5C727350682F8293}" {
     m_eSlotTypes GROUP_SMALL
    }
   }
  }
  SCR_EntityCatalogEntry "{693A9951EFBD8C71}" {
   m_sEntityPrefab "{2282FDD9DDACD45E}Prefabs/Characters/Role Loadouts/Character_RTG_TeamLeader.et"
   m_aEntityDataList {
    SCR_EntityCatalogEditorData "{6052CE8EFD185AFB}" {
     m_eValidEditorModes 33
    }
    SCR_EntityCatalogSpawnerData "{5C727350682F8293}" {
     m_eSlotTypes GROUP_SMALL
    }
   }
  }
 }
}