SCR_EntityCatalogMultiList {
 m_eEntityCatalogType VEHICLE
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{6938D5A40AA81DCA}" {
   m_sIdentifier "Ground"
   m_aEntities {
    SCR_EntityCatalogEntry "{6938D5A404A2AA18}" {
     m_sEntityPrefab "{8203FEF7C468F011}Prefabs/Vehicles/Wheeled/GMV.et"
    }
    SCR_EntityCatalogEntry "{6938D5A4059C410A}" {
     m_sEntityPrefab "{2B483B0A8C96BD16}Prefabs/Vehicles/Wheeled/CMV.et"
    }
   }
  }
  SCR_EntityCatalogMultiListEntry "{69388CF506489A74}" {
   m_sIdentifier "Helicopters"
   m_aEntities {
    SCR_EntityCatalogEntry "{69388CF505B90F73}" {
     m_sEntityPrefab "{0AE1A39BCBDA9CAF}Prefabs/Vehicles/Helicopters/AH6M/RTG_Sparrow_Transport.et"
     m_aEntityDataList {
      SCR_EntityCatalogEditorData "{65F803942541EB0F}" {
       m_eValidEditorModes 33
      }
      SCR_EntityCatalogSpawnerData "{65F803942541EB08}" {
       m_eSlotTypes VEHICLE_LARGE
      }
     }
    }
    SCR_EntityCatalogEntry "{69388CF5035F4A59}" {
     m_sEntityPrefab "{D27359F6ADF11EF9}Prefabs/Vehicles/Helicopters/AH6M/RTG_Sparrow_Supply.et"
     m_aEntityDataList {
      SCR_EntityCatalogEditorData "{65F803942541EB0F}" {
       m_eValidEditorModes 33
      }
      SCR_EntityCatalogSpawnerData "{65F803942541EB08}" {
       m_eSlotTypes VEHICLE_LARGE
      }
     }
    }
    SCR_EntityCatalogEntry "{69388CF50284AAF2}" {
     m_sEntityPrefab "{6E5F4845EA4BD45C}Prefabs/Vehicles/Helicopters/AH6M/RTG_Sparrow_Attack.et"
     m_aEntityDataList {
      SCR_EntityCatalogEditorData "{65F803942541EB0F}" {
       m_eValidEditorModes 33
      }
      SCR_EntityCatalogSpawnerData "{65F803942541EB08}" {
       m_eSlotTypes VEHICLE_LARGE
      }
     }
    }
   }
  }
 }
}