SCR_ArsenalItemTypeUIConfig {
 m_ArsenalItemUITypes {
  SCR_ArsenalItemTypeUI "{693865410BB71FA2}" {
   m_eItemType RTG_ANTITANK
   m_Info SCR_UIInfo "{69386540FD1C5E00}" {
    Name "[RTG] Anti Tank"
    Description "RTG Custom Arsenal Class"
    Icon "{10840233D666C940}UI/Textures/Editor/Attributes/Arsenal/Attribute_Arsenal_Launcher.edds"
   }
  }
  SCR_ArsenalItemTypeUI "{69386540EDDB37FA}" {
   m_eItemType RTG_TEAMLEADER
   m_Info SCR_UIInfo "{69386540EDDB37AD}" {
    Name "[RTG] Team Leader"
    Description "RTG Custom Arsenal Class"
    Icon "{4B4A98921A5C3583}UI/Textures/Editor/Attributes/Arsenal/Attribute_Arsenal_Radio.edds"
   }
  }
  SCR_ArsenalItemTypeUI "{69386540DA2116DF}" {
   m_eItemType RTG_AUTORIFLEMAN
   m_Info SCR_UIInfo "{69386540DA211696}" {
    Name "[RTG] Auto Rifleman"
    Description "RTG Custom Arsenal Class"
    Icon "{A02EB3B80E276400}UI/Textures/Editor/Attributes/Arsenal/Attribute_Arsenal_MachineGuns.edds"
   }
  }
  SCR_ArsenalItemTypeUI "{69386540C5D70045}" {
   m_eItemType RTG_AMMOBEARER
   m_Info SCR_UIInfo "{69386540C5D703FA}" {
    Name "[RTG] Ammo Bearer"
    Description "RTG Custom Arsenal Class"
    Icon "{769B709DF200BF84}UI/Textures/Editor/Attributes/Arsenal/Attribute_Arsenal_Backpacks.edds"
   }
  }
  SCR_ArsenalItemTypeUI "{69386540B617ED91}" {
   m_eItemType RTG_MEDIC
   m_Info SCR_UIInfo "{69386540B617ED52}" {
    Name "[RTG] Medic"
    Description "RTG Custom Arsenal Class"
    Icon "{CDF868B16669B7EA}UI/Textures/Editor/Attributes/Arsenal/Attribute_Arsenal_Medical.edds"
   }
  }
  SCR_ArsenalItemTypeUI "{69386540AB0B7FDA}" {
   m_eItemType RTG_LOGI
   m_Info SCR_UIInfo "{69386540AB0B7F9E}" {
    Name "[RTG] Logi"
    Description "RTG Custom Arsenal Class"
    Icon "{CDF94F179A33CFB9}UI/Textures/Editor/Attributes/Arsenal/Attribute_Arsenal_Accessories.edds"
   }
  }
  SCR_ArsenalItemTypeUI "{693865409B7B7280}" {
   m_eItemType RTG_CREWMAN
   m_Info SCR_UIInfo "{693865409B7B7244}" {
    Name "[RTG] Crewman"
    Description "RTG Custom Arsenal Class"
    Icon "{449F74AB601B3ADC}UI/Textures/Editor/ContentBrowser/ContentBrowser_Trait_Management_Mortar.edds"
   }
  }
  SCR_ArsenalItemTypeUI "{6938654091C4E452}" {
   m_eItemType RTG_PILOT
   m_Info SCR_UIInfo "{6938654091C4E415}" {
    Name "[RTG] Pilot"
    Description "RTG Custom Arsenal Class"
    Icon "{2EEBBBCA36DD775F}UI/Textures/Editor/Attributes/Arsenal/Attribute_Arsenal_Pistols.edds"
   }
  }
 }
}