SCR_EditableEntityCore {
 m_EntityLabels {
  SCR_EditableEntityCoreLabelSettingExtended "{6938654277715330}" {
   m_Info SCR_UIInfo "{6938654255ACA1E1}" {
    Name "Raider Tactical Group"
    Icon "{D85F4BE8C948DFEC}Images/RTG_LOGO_V2_NO_BACK.edds"
   }
   m_LabelType FACTION_RTG
   m_LabelGroupType FACTION
   m_eBlackListedModes BUILDING
  }
 }
}