SCR_MissionHeader {
 World "{31ECC9059F904B6C}Worlds/RTG_Cain_Base.ent"
 m_sName "[RTG] Cain Gamemaster"
 m_sAuthor "R&D"
 m_sDescription "The base rtg mission for Cain"
 m_sGameMode "#AR-Scenario_GameMode_GameMaster"
 m_iPlayerCount 64
 m_ACE_Settings ACE_MissionHeaderSettings "{693C6B0E5D841568}" {
  m_ACE_Finger_Settings ACE_Finger_Settings "{693C6B0E2560CB97}" {
   m_bCanPingAttach 0
   m_fPingRangeM 18
   m_fMapPointingRangeM 18
  }
  m_ACE_Medical_Core ACE_Medical_Core_Settings "{693C6B0E226C3125}" {
   m_fResilienceDamageScale 0.6
   m_fBleedingRateScale 0.8
   m_fSecondChanceOnHead 1
   m_bSecondChanceForFallDamageEnabled 1
  }
  m_ACE_Medical_Hitzones ACE_Medical_Hitzones_Settings "{693C6B0E225D9331}" {
  }
 }
}